In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
students = np.array([
    [101, 18, 85, 78, 92, 88],
    [102, 19, 72, 85, 79, 81],
    [103, 18, 95, 91, 89, 94],
    [104, 20, 68, 74, 70, 72],
    [105, 19, 88, 82, 85, 90],
    [106, 21, 76, 69, 80, 75],
    [107, 20, 91, 87, 93, 89],
    [108, 18, 64, 71, 68, 70],
    [109, 19, 83, 79, 88, 84],
    [110, 21, 97, 94, 96, 98]
])

# Columns:
# Student_ID, Age, Math, Physics, Chemistry, Final_Score

## **Basic Inspection**

Q1. What is the shape of the array?

Q2. How many students are there?

Q3. How many features/columns are there?

Q4. What is the data type?

Q5. Display the first 5 rows.

Q6. Display the last 3 rows.

In [3]:
# Shape Of Dataset
students.shape

(10, 6)

In [4]:
# How many student are there?
len(students)

10

In [5]:
# How many features/columns are there?
len(students[0])

6

In [6]:
# What is the data type?
type(students)

numpy.ndarray

In [7]:
# Display first 5 Rows
students[:5]

array([[101,  18,  85,  78,  92,  88],
       [102,  19,  72,  85,  79,  81],
       [103,  18,  95,  91,  89,  94],
       [104,  20,  68,  74,  70,  72],
       [105,  19,  88,  82,  85,  90]])

In [8]:
# Display last 3 Rows
students[-3:]

array([[108,  18,  64,  71,  68,  70],
       [109,  19,  83,  79,  88,  84],
       [110,  21,  97,  94,  96,  98]])

## **Indexing and Slicing**

Q7. Get the first student.

Q8. Get the last student.

Q9. Get students 1–5.

Q10. Get only the Math column.

Q11. Get only the Final_Score column.

Q12. Get Math, Physics and Chemistry columns.

Q13. Get the first 5 students' Math scores.

Q14. Get the last 5 students' Final_Score.

Q15. Get rows 3–7 and columns Math–Chemistry.

In [9]:
# Get the first and the last Index
first_index = students[0]
print(first_index)

last_index = students[-1]
print(last_index)

[101  18  85  78  92  88]
[110  21  97  94  96  98]


In [10]:
# Get Student 1-5
students[0:5]

array([[101,  18,  85,  78,  92,  88],
       [102,  19,  72,  85,  79,  81],
       [103,  18,  95,  91,  89,  94],
       [104,  20,  68,  74,  70,  72],
       [105,  19,  88,  82,  85,  90]])

In [11]:
# Get only the maths columns
students[:,2]

array([85, 72, 95, 68, 88, 76, 91, 64, 83, 97])

In [12]:
# Get only the final score column
students[:,-1]

array([88, 81, 94, 72, 90, 75, 89, 70, 84, 98])

In [13]:
# Get Math, Physics and Chemistry
students[:,2:5]

array([[85, 78, 92],
       [72, 85, 79],
       [95, 91, 89],
       [68, 74, 70],
       [88, 82, 85],
       [76, 69, 80],
       [91, 87, 93],
       [64, 71, 68],
       [83, 79, 88],
       [97, 94, 96]])

In [14]:
# Get the first 5 students' Math scores.
students[:5,2]

array([85, 72, 95, 68, 88])

In [15]:
# Get the last 5 students' Final_Score.
students[-5:,-1]

array([75, 89, 70, 84, 98])

In [16]:
# Get rows 3–7 and columns Math–Chemistry.
students[2:7,2:5]

array([[95, 91, 89],
       [68, 74, 70],
       [88, 82, 85],
       [76, 69, 80],
       [91, 87, 93]])

## **Statistics**

Q16. Find the average Math score.

Q17. Find the average Physics score.

Q18. Find the average Chemistry score.

Q19. Find the average Final_Score.

Q20. Find the highest Math score.

Q21. Find the lowest Math score.

Q22. Find the median Final_Score.

Q23. Find the standard deviation of Final_Score.

Q24. Calculate the average of each subject.

Q25. Calculate the average score for each student.

In [17]:
print("Math Average : " ,students[:,2].mean())
print("Physics Average : " ,students[:,3].mean())
print("Chemistry Average : " ,students[:,4].mean())
print("Final Score Average : " ,students[:,5].mean())

Math Average :  81.9
Physics Average :  81.0
Chemistry Average :  84.0
Final Score Average :  84.1


In [18]:
print("Highest Maths Score : ", students[:,2].max())
print("Lowest Maths Score : ", students[:,2].min())

Highest Maths Score :  97
Lowest Maths Score :  64


In [19]:
print("Median of final Score : ", np.median(students[:,-1]))

Median of final Score :  86.0


In [20]:
print("Standard Deviation of Final Score : ", np.std(students[:,-1]))

Standard Deviation of Final Score :  8.960468737739115


In [21]:
print("Average Marks of Students : \n" , np.mean(students[:,2:5],axis = 1).reshape(-1,1))

Average Marks of Students : 
 [[85.        ]
 [78.66666667]
 [91.66666667]
 [70.66666667]
 [85.        ]
 [75.        ]
 [90.33333333]
 [67.66666667]
 [83.33333333]
 [95.66666667]]


## **Boolean Masking**

Q26. Find students with Math > 80.

Q27. Find students with Final_Score > 90.

Q28. Find students with Physics < 75.

Q29. Find students whose Math score is between 70 and 90.

Q30. Find students who scored > 85 in both Math AND Physics.

Q31. Find students who scored > 90 in Math OR Chemistry.

In [22]:
students[students[:,2] > 80]

array([[101,  18,  85,  78,  92,  88],
       [103,  18,  95,  91,  89,  94],
       [105,  19,  88,  82,  85,  90],
       [107,  20,  91,  87,  93,  89],
       [109,  19,  83,  79,  88,  84],
       [110,  21,  97,  94,  96,  98]])

In [23]:
students[students[:,-1] > 90]

array([[103,  18,  95,  91,  89,  94],
       [110,  21,  97,  94,  96,  98]])

In [24]:
students[students[:,3] < 75]

array([[104,  20,  68,  74,  70,  72],
       [106,  21,  76,  69,  80,  75],
       [108,  18,  64,  71,  68,  70]])

In [25]:
students[(students[:,2] >= 70) & (students[:,2] <= 90)]

array([[101,  18,  85,  78,  92,  88],
       [102,  19,  72,  85,  79,  81],
       [105,  19,  88,  82,  85,  90],
       [106,  21,  76,  69,  80,  75],
       [109,  19,  83,  79,  88,  84]])

In [26]:
students[(students[:, 2] > 85) & (students[:, 3] > 85)]

array([[103,  18,  95,  91,  89,  94],
       [107,  20,  91,  87,  93,  89],
       [110,  21,  97,  94,  96,  98]])

In [27]:
students[(students[:, 2] > 90) | (students[:, 4] > 90)]

array([[101,  18,  85,  78,  92,  88],
       [103,  18,  95,  91,  89,  94],
       [107,  20,  91,  87,  93,  89],
       [110,  21,  97,  94,  96,  98]])

## **Where(), argmax() and argmin()**

Q32. Find the index of the student with the highest Final_Score.

Q33. Find the Student_ID of the highest-scoring student.

Q34. Find the Student_ID of the lowest-scoring student.

Q35. Find the highest score in each subject.

Q36. Find the lowest score in each subject.

Q37. Use np.where() to identify students who passed
    Final_Score >= 75.

In [28]:
np.argmax(students[:,-1])

np.int64(9)

In [29]:
students[np.argmax(students[:,-1]),0]

np.int64(110)

In [30]:
students[np.argmin(students[:,-1]),0]

np.int64(108)

In [31]:
students[:, 2:5].max(axis=0)

array([97, 94, 96])

In [32]:
students[:, 2:5].min(axis=0)

array([64, 69, 68])

In [33]:
np.where(students[:, 5] >= 75)

(array([0, 1, 2, 4, 5, 6, 8, 9]),)

## **Axis Practice**

Q38. Calculate the mean of each column.

Q39. Calculate the mean of each row.

Q40. Find the maximum value of each column.

Q41. Find the minimum value of each row.

Q42. Calculate the standard deviation of each subject.

Q43. Explain in a comment what axis=0 and axis=1
    mean in this dataset.

In [34]:
np.mean(students, axis=0)

array([105.5,  19.3,  81.9,  81. ,  84. ,  84.1])

In [35]:
np.mean(students,axis=1)

array([77.        , 73.        , 81.66666667, 68.        , 78.16666667,
       71.16666667, 81.16666667, 66.5       , 77.        , 86.        ])

In [36]:
students.max(axis=0)

array([110,  21,  97,  94,  96,  98])

In [37]:
students.min(axis=1)

array([18, 19, 18, 20, 19, 21, 20, 18, 19, 21])

In [38]:
np.std(students[:,2:5], axis = 0)

array([10.8485022 ,  7.9246451 ,  9.07744457])

In [39]:
# axis=0 → work DOWN the columns
# Mean of each subject
students[:, 2:5].mean(axis=0)

array([81.9, 81. , 84. ])

In [40]:
# axis=1 → work ACROSS the rows
# Mean of each student
students[:, 2:5].mean(axis=1)

array([85.        , 78.66666667, 91.66666667, 70.66666667, 85.        ,
       75.        , 90.33333333, 67.66666667, 83.33333333, 95.66666667])

## **Reshaping & Manipulation**

Q44. Extract all subject scores into a separate array.

Q45. Reshape the subject-score array into a suitable shape.

Q46. Flatten the subject-score array.

Q47. Transpose the subject-score matrix.

Q48. Create a new column containing the average
    of Math, Physics and Chemistry.

In [41]:
subjects = students[:,2:5]
print(subjects)

[[85 78 92]
 [72 85 79]
 [95 91 89]
 [68 74 70]
 [88 82 85]
 [76 69 80]
 [91 87 93]
 [64 71 68]
 [83 79 88]
 [97 94 96]]


In [42]:
subjects.reshape(5,6)

array([[85, 78, 92, 72, 85, 79],
       [95, 91, 89, 68, 74, 70],
       [88, 82, 85, 76, 69, 80],
       [91, 87, 93, 64, 71, 68],
       [83, 79, 88, 97, 94, 96]])

In [43]:
subjects.flatten()

array([85, 78, 92, 72, 85, 79, 95, 91, 89, 68, 74, 70, 88, 82, 85, 76, 69,
       80, 91, 87, 93, 64, 71, 68, 83, 79, 88, 97, 94, 96])

In [44]:
subjects.T

array([[85, 72, 95, 68, 88, 76, 91, 64, 83, 97],
       [78, 85, 91, 74, 82, 69, 87, 71, 79, 94],
       [92, 79, 89, 70, 85, 80, 93, 68, 88, 96]])

In [45]:
average = students[:, 2:5].mean(axis=1).reshape(-1, 1)
print(average)

[[85.        ]
 [78.66666667]
 [91.66666667]
 [70.66666667]
 [85.        ]
 [75.        ]
 [90.33333333]
 [67.66666667]
 [83.33333333]
 [95.66666667]]


## **Normalization & Standardization**

Q49. Perform Min-Max normalization.

Formula:
(x - min) / (max - min)

Q50. Standardize the subject scores.

Formula:
(x - mean) / std

Q51. Verify that your standardized data has
    approximately mean = 0.

Q52. Verify that its standard deviation is
    approximately 1.

In [46]:
subjects = students[:, 2:5]
normalized = (subjects - subjects.min(axis=0)) / (subjects.max(axis=0) - subjects.min(axis=0))
print(normalized)

[[0.63636364 0.36       0.85714286]
 [0.24242424 0.64       0.39285714]
 [0.93939394 0.88       0.75      ]
 [0.12121212 0.2        0.07142857]
 [0.72727273 0.52       0.60714286]
 [0.36363636 0.         0.42857143]
 [0.81818182 0.72       0.89285714]
 [0.         0.08       0.        ]
 [0.57575758 0.4        0.71428571]
 [1.         1.         1.        ]]


In [47]:
subjects = students[:, 2:5]
standardized = (subjects - subjects.mean(axis=0)) / subjects.std(axis=0)

print(standardized)

[[ 0.28575373 -0.37856585  0.8813053 ]
 [-0.91256837  0.50475447 -0.55081581]
 [ 1.20753997  1.26188616  0.55081581]
 [-1.28128287 -0.88332031 -1.54228427]
 [ 0.5622896   0.12618862  0.11016316]
 [-0.54385388 -1.5142634  -0.44065265]
 [ 0.83882547  0.7571317   0.99146846]
 [-1.64999736 -1.26188616 -1.7626106 ]
 [ 0.10139649 -0.25237723  0.44065265]
 [ 1.39189721  1.64045201  1.32195795]]


In [48]:
standardized.mean(axis=0)

array([-5.55111512e-16,  0.00000000e+00,  2.22044605e-17])

In [49]:
standardized.std(axis=0)

array([1., 1., 1.])

# **Machine Learning Style Implementation Sheet**

Q53. Create X and y.

Q54. Check X.shape and y.shape.

Q55. Calculate X.mean(axis=0).

Q56. Standardize X.

Q57. Create random train/test indices.

Q58. Split the data into 80% training and 20% testing.

Q59. Check the shapes of X_train, X_test,
    y_train and y_test.

Q60. Calculate the mean of each training feature.

Q61. Use those training statistics to standardize
    both training and test data.

In [50]:
# Create features X and target Y
# X = Math, Physics, Chemistry
# y = Final_Score

X = students[:, 2:5]
Y = students[:, -1]

In [51]:
# Shape of X
X.shape

(10, 3)

In [52]:
# Shape of Y
Y.shape

(10,)

In [53]:
# Mean of X
X.mean(axis=0)

array([81.9, 81. , 84. ])

In [54]:
# Standardized
X_standardized = (X - X.mean(axis=0)) / X.std(axis=0)
print(X_standardized)

[[ 0.28575373 -0.37856585  0.8813053 ]
 [-0.91256837  0.50475447 -0.55081581]
 [ 1.20753997  1.26188616  0.55081581]
 [-1.28128287 -0.88332031 -1.54228427]
 [ 0.5622896   0.12618862  0.11016316]
 [-0.54385388 -1.5142634  -0.44065265]
 [ 0.83882547  0.7571317   0.99146846]
 [-1.64999736 -1.26188616 -1.7626106 ]
 [ 0.10139649 -0.25237723  0.44065265]
 [ 1.39189721  1.64045201  1.32195795]]


In [55]:
# Create random train/test indices
np.random.seed(42)                 # same random result every time
indices = np.random.permutation(len(X))
print(indices)

[8 1 5 0 7 2 9 4 3 6]


In [56]:
# Split the data into 80% training and 20% testing
split = int(0.8 * len(X))
train_indices = indices[:split]
test_indices = indices[split:]

X_train = X[train_indices]
X_test = X[test_indices]

Y_train = Y[train_indices]
Y_test = Y[test_indices]

In [57]:
# Check the shapes of X_train, X_test, y_train and y_test.
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("Y_train shape:", Y_train.shape)
print("Y_test shape:", Y_test.shape)

X_train shape: (8, 3)
X_test shape: (2, 3)
Y_train shape: (8,)
Y_test shape: (2,)


In [58]:
# Calculate the mean of each training feature.
X_train_mean = X_train.mean(axis=0)
print(X_train_mean)

[82.5   81.125 84.625]


In [59]:
# Use those training statistics to standardize both training and test data.
X_train_standardized = (X_train - X_train_mean) / X_train.std(axis=0)
X_test_standardized = (X_test - X_train_mean) / X_train.std(axis=0)