## **Learn about NumPy**

In [1]:
import numpy as np
import time

### Creating Array from list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array : ", arr_1d)

1D Array :  [1 2 3 4 5]


In [3]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array : ", arr_2d)

2D Array :  [[1 2 3]
 [4 5 6]]


### List vs NumPy Array

In [4]:
py_list = [1,2,3]
print("Python List multiplication ", py_list * 2)

py_array = np.array([1,2,3])
print("Python Array multiplication ", py_array * 2)

Python List multiplication  [1, 2, 3, 1, 2, 3]
Python Array multiplication  [2 4 6]


In [5]:
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List operation time : " ,time.time() - start)

start = time.time()
py_array = np.arange(100000) * 2
print("\n Numpy operation time : ", time.time()- start)


 List operation time :  0.015921354293823242

 Numpy operation time :  0.0027692317962646484


### Creating array from scratch

In [6]:
zeros = np.zeros((3,4))
print("Zero Matrix : \n", zeros)

ones = np.ones((3,4))
print("\n Ones Matrix : \n", ones)

empty = np.empty((3,4))
print("\n Empty Matrix : \n", empty)

full = np.full((3,4),5)
print("\n Full Matrix : \n", full)

identity = np.eye(3)
print("\n Identity Matrix : \n", identity)

random = np.random.random((3,4))
print("\n Random Matrix : \n", random)

Zero Matrix : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 Ones Matrix : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 Empty Matrix : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 Full Matrix : 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

 Identity Matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Random Matrix : 
 [[0.52823326 0.40570248 0.97123059 0.05296625]
 [0.65378274 0.59793661 0.08764917 0.0171394 ]
 [0.32817557 0.99834692 0.62847524 0.45534861]]


### Vector, Matrix and Tensor

In [7]:
vector = np.array([1,2,3])
print("Vector : ",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("\nMatrix : ",matrix)

tensor = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
print("\nTensor : ",tensor)

Vector :  [1 2 3]

Matrix :  [[1 2 3]
 [4 5 6]]

Tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Numpy / Array Properties

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print("Shape : ", arr.shape)
print("Size : ", arr.size)
print("Dimension : ", arr.ndim)
print("Data Type : ", arr.dtype)

Shape :  (2, 3)
Size :  6
Dimension :  2
Data Type :  int64


In [9]:
# Reshape array
arr = np.arange(12)
print("Original Array : ", arr)

reshaped = arr.reshape((3,4))
print("\nReshaped Array : ", reshaped)

flattened = reshaped.flatten()
print("\nFlattened Array : ", flattened)

transposed = reshaped.transpose()
print("\nTransposed Array : ", transposed)

Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed Array :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## **Numpy** **Array** **Operation**

In [10]:
arr = np.array([1,2,3,4,5,6])
print("Basic Slicing : ",arr[2:5])
print("With Step : ", arr[1:5:2])
print("Negative Indexing : ", arr[-3])

Basic Slicing :  [3 4 5]
With Step :  [2 4]
Negative Indexing :  4


In [11]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print("Speciic Element : ",arr_2d[1,2])
print("Entire Row : ", arr_2d[1])
print("Entire Row : ", arr_2d[:, 1])

Speciic Element :  6
Entire Row :  [4 5 6]
Entire Row :  [2 5]


In [12]:
# Sorting
unsorted = np.array([3,1,4,5,6,3,9,67,43,2,1])
print("Unsorted Array : ", unsorted)

sorted = np.sort(unsorted)
print("Sorted Array : ", sorted)

unsorted_2d = np.array([[3,9,4],[5,8,7]])
print("Unsorted 2D Array : ", unsorted_2d)

sorted_2d = np.sort(unsorted_2d,axis = 0) # Use axis 0 to sort columns and axis 1 row wise
print("Sorted 2D Array : ", sorted_2d)
#

Unsorted Array :  [ 3  1  4  5  6  3  9 67 43  2  1]
Sorted Array :  [ 1  1  2  3  3  4  5  6  9 43 67]
Unsorted 2D Array :  [[3 9 4]
 [5 8 7]]
Sorted 2D Array :  [[3 8 4]
 [5 9 7]]


### Adding and Removing data

In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print("Concatenation : ", np.concatenate((arr1,arr2)))

Concatenation :  [1 2 3 4 5 6]


### **Where**

In [14]:
a = np.array([10,20,30,40,50,60])
print(np.where(a > 25))
print("OR")
print(np.where(a > 25, 1, 0))

(array([2, 3, 4, 5]),)
OR
[0 0 1 1 1 1]
